apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pftlv4x90-nodejs 
  janus-idp.io/tekton: pftlv4x90-nodejs
  backstage.io/kubernetes-id: pftlv4x90-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pftlv4x90-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  