apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pftlv4x90-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pftlv4x90-nodejs 
  name: pftlv4x90-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pftlv4x90-nodejs 
